In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [2]:
data= pd.read_csv('datasets/HD_data.csv')

In [3]:
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       297 non-null    int64
 1   sex       297 non-null    int64
 2   cp        297 non-null    int64
 3   trestbps  297 non-null    int64
 4   chol      297 non-null    int64
 5   fbs       297 non-null    int64
 6   restecg   297 non-null    int64
 7   thalach   297 non-null    int64
 8   exang     297 non-null    int64
 9   oldpeak   297 non-null    float64
 10  slope     297 non-null    int64
 11  ca        297 non-null    int64
 12  thal      297 non-null    int64
 13  target    297 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 32.6 KB

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [4]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,54,1,0,110,239,0,1,126,1,2.8,1,1,3,0
1,57,1,0,165,289,1,0,124,0,1.0,1,3,3,0
2,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
3,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
4,49,1,1,130,266,0,1,171,0,0.6,2,0,2,1

In [5]:
X=data.drop(columns='target',axis=1)
Y=data['target']

In [6]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2, stratify=Y, random_state=42)

In [7]:
model_RFC = RandomForestClassifier(n_estimators=300, criterion='gini', max_depth=300, bootstrap=True, max_samples= None)
model_RFC.fit(X_train, Y_train)

RandomForestClassifier(max_depth=300, n_estimators=300)

In [8]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
y_pred = model_RFC.predict(X_test)
accuracy = accuracy_score(Y_test, y_pred)
precision = precision_score(Y_test, y_pred, average='weighted')
recall = recall_score(Y_test, y_pred, average='weighted')
f1 = f1_score(Y_test, y_pred, average='weighted')
cm = confusion_matrix(Y_test, y_pred)

print(f'Accuracy: {accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1 Score: {f1}')
print(f'Confusion Matrix:\n{cm}')

Accuracy: 0.8833333333333333
Precision: 0.8883333333333333
Recall: 0.8833333333333333
F1 Score: 0.8836257309941521
Confusion Matrix:
[[25  2]
 [ 5 28]]

In [22]:
import pickle
filename = "heart_disease_model.pkl"
pickle.dump(model_RFC, open(filename, "wb"))